### Create a new item ###
POST http://localhost:8000/create/1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com"
}

### Create a new item 2 ###
POST http://localhost:8000/create/2
Content-Type: application/json

{
    "name": "Wachira Duangdee",
    "email": "Wachira@example.com"
}

### Get an item ###
GET http://localhost:8000/read/1

### Get an item ###
GET http://localhost:8000/read/2

### Update an item ###
PUT http://localhost:8000/update/1
Content-Type: application/json

{
    "name": "Updated John Doe2222",
    "email": "updatedjohndoe@example.com"
}

### Get the updated item ###
GET http://localhost:8000/read/1

### Delete an item ###
DELETE http://localhost:8000/delete/1

### Get the deleted item (should return 404) ###
GET http://localhost:8000/read/1
